const TeamStatements = () => {
    return (
        <div className="card team-statements">
            <p>In our quest to capture the true essence of each lion, Gluten and I navigated an intricate dance of artistry and precision. Our journey, marked by the constant interplay of software limitations and raw determination, birthed art that not just replicated but celebrated the original charm. Determining each trait was an exercise in creativity and compromise; challenging yet deeply rewarding. From musing on the enigma of a pirate hat-police shirt combination to ensuring that no two traits clashed, every decision was laced with an aim to stay true to the lion's spirit.</p>
            <p>In this voyage, I discovered not just the joy of creation, but the magic of camaraderie. Every stroke, every pixel adjustment, was a shared endeavor. And as you witness your lion in its full splendor, I hope you sense the passion, the debates, and the fun that went into its making. Dive into the world of Lazy Butts with an open heart, savor the unexpected delights, and bask in the enchantment we've lovingly crafted.</p>
            <p style={{ fontFamily: 'Permanent Marker' }}>~John the Craftsman</p>
            <p>Collaborating on the Lazy Lions traits was a profound experience for me. Delving deep into the intricacies of their art style, I gained invaluable insights and honed my techniques. Crafting the lower portion of the lions presented its own unique challenges. While some designs were straightforward, others demanded meticulous deconstruction and reconstruction to achieve our vision. This journey has not only enriched my artistic skillset but also underscored my passion for detail and precision.</p>
            <p style={{ fontFamily: 'Permanent Marker' }}>~Gluten Free</p>
            <p>In spearheading the Lazy Butts project, I've had the unique opportunity to blend my deep-seated passion for technology with the dynamic realm of NFTs. From crafting the intricate details of image generation to weaving the robust solidity contracts, every step has been a testament to the vastness and versatility of web3. My journey stretched beyond just code; it encompassed architecting backend APIs, designing an intuitive React front-end, and ensuring optimal AWS management.</p>
            <p>This project, while challenging, has been a true testament to the potential of decentralized platforms and the transformative power of community-driven initiatives. As the sole developer on board, it has been a privilege to lay the technical foundation upon which our community can thrive and create. I'm deeply proud of what we've achieved and look forward to where this technology and our collective imagination will take us next.</p>
            <p style={{ fontFamily: 'Permanent Marker' }}>~crypt0potamus</p>
            <p>Lazy Butts emerged from a simple yet profound desire: amplifying our #ROAR. My love and pride for my lion always pushed me to seek avenues where I could showcase it more vividly, more dynamically. And why stop at just admiration? I dreamt of evolving its presence, building upon its majestic aura, and weaving it into even grander narratives.</p>
            <p>But a dream remains just that without the right catalysts. It was the sheer serendipity of being amidst a galaxy of gifted creators that transformed this vision into a palpable reality. Together, we embarked on this journey, not just for my lion or theirs, but for the entire Pride.</p>
            <p>The result is in front of you, a testament to our collective passion and creativity. I hope that when you see, share, and live the Lazy Butts experience, it brings you as much joy as we felt in its making.</p>
            <p style={{ fontFamily: 'Permanent Marker' }}>~localcryptogod</p>
        </div>
    )
}

export default TeamStatements